spring:
  datasource:
    url: jdbc:mysql://10.10.10.111:4306/xsun_group?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: xsun_group
    password: kqh9845lddGFdb5E
  redis:
    database: 0
swagger:
  enable: true
##加密
jasypt:
  encryptor:
    password: xinya123456

comm:
  switch:
    sms: false