spring:
  datasource:
    url: jdbc:mysql://10.10.10.111:5306/xsun_group?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: xsun_group
    password: 3Ar7PNJ0lRsQ1BPJ
  redis:
    database: 1
swagger:
  enable: true
##加密
jasypt:
  encryptor:
    password: xinya123456

comm:
  switch:
    sms: false