spring:
  datasource:
    url: jdbc:mysql://10.10.10.212:4306/xsun_group?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: xsun_group
    password: 1iDnwwKq2QNRfD9N
  redis:
    database: 2
swagger:
  enable: true

comm:
  switch:
    sms: false